#!/bin/bash
# fine_tune_yolo_drowning.sh

# Force use of GPU 1
export CUDA_VISIBLE_DEVICES=0

# Activate conda environment
source ~/anaconda3/etc/profile.d/conda.sh
conda activate yolov8detection

# Run YOLOv8 training (baseline)
yolo detect train \
    data="data.yaml"\
    model= yolov8m.pt\
    epochs=100 \
    imgsz=640 \
    batch=16 \
    device=0
